version: '2'
services:
  repo4-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/repo4/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=repo4
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
